name: Product Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Publishing:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Env
        run: |
          VERSION_NAME=$(grep "versionName" ./version.properties | cut -d "=" -f 2)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          
          mkdir -p ./.gnupg
          
          echo ${{ secrets.GRADLE_PROPERTIES }} | openssl base64 -d -A -out ./gradle.properties
          echo ${{ secrets.PUBLISH_PROPERTIES }} | openssl base64 -d -A -out ./publish.properties
          echo ${{ secrets.SIGNING_KEY }} | openssl base64 -d -A -out ./.gnupg/secring.gpg

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK (Only on Act)
        if: ${{ success() && env.ACT }}
        uses: android-actions/setup-android@v3

      - name: Publish
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION_NAME }}
          allowUpdates: false
          skipIfReleaseExists: true
          generateReleaseNotes: true
